### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by MariusVolkhart** [bsycorp/gradle-jib-plugin#1]
Hi,

I noticed that there's no license attached with the repo or source code. Naturally, I respect your decision if you don't wish to license this code for others, but given your FYI post in the Jib repo and the public nature of this repo, I assume the lack of license is an accidental oversight. If so, would you mind specifying the license under which you intend this code to be used?

**Comment by nhoughto** [comment]
Yep an oversight, let me fix..

**Comment by MariusVolkhart** [comment]
Sweet, thanks!
